---
title: 'STAT 405 Project'
format:
  pdf: default
 
pdf-engine: pdflatex  # You may need to remove this line
echo: false
---



<br />


```{r}
#install.packages("readr")
library(readr)

data_set <- read_csv("Hospital_Inpatient_Discharges__SPARCS_De-Identified___2013.csv",show_col_types = FALSE)

cleaned_data <- na.omit(data_set)

```

<br />

```{r}
y <- cleaned_data$`Total Charges`
```


```{r}
length_of_stay <- strtoi(cleaned_data$`Length of Stay`)
plot(length_of_stay, y,  xlab = "Length of Stay", main = "Price vs Length of Stay", ylab = "Price")

lmfs <- lm(y ~ length_of_stay)
abline(lmfs, col = "RED")
```


```{r}

boxplot(cleaned_data$'Total Costs', 
        main="Box Plot of Total Costs",
        ylab= "Total costs")
```


```{r}
options(repr.plot.width = 100, repr.plot.height = 100)

cleaned_data$`Payment Typology 1` <- as.factor(cleaned_data$`Payment Typology 1`)
payments <- table(cleaned_data$`Payment Typology 1`)
pie(payments, main = "Payment Type Distribution", col=rainbow(length(payments)), labels = NA)
legend("left", legend = levels(cleaned_data$`Payment Typology 1`), fill = rainbow(length(payments)), cex = 0.7)
```


```{r}

# Create the line chart
plot(cleaned_data$`Length of Stay`, cleaned_data$`Total Charges`, type = "l", col = "blue", xlab = "Length of Stay", ylab = "Total Charges", main = "Trends in Total Charges and Length of Stay")

# Add a line for Total Costs
lines(cleaned_data$`Birth Weight`, cleaned_data$`Total Costs`, col = "red")

# Add a legend
legend("topright", legend = c("Total Charges", "Total Costs"), col = c("blue", "red"), lty = 1)

# Add a grid
grid()


#Total cost doesn't change even if length of stay increases and total charge increases.


```
```{r}

heatmap_data <- table(cleaned_data$`Age Group`, cleaned_data$Gender)


row_names <- as.factor(rownames(heatmap_data))
col_names <- as.factor(colnames(heatmap_data))


heatmap(heatmap_data,
        Rowv = NA,          
        Colv = NA,       
        col = colorRampPalette(c("white", "blue"))(50),  
        xlab = "Gender",    
        main = "Gender v. Age Group",  
        labRow = row_names, 
        labCol = col_names) 

```
```{r}
ageGroups <- table(cleaned_data$`Age Group`)
barplot(ageGroups, main = "Age Group Distribution", xlab = "Age Group", 
        ylab = "Frequency", col = "green", border = "black", ylim = c(0, 300000)) 
```

<br />




